version: "3.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: es-node1
    environment:
      - node.name=elasticsearch
      - cluster.name=datasearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #   - cluster.initial_master_nodes=elasticsearch
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es-net
           
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_URL=http://es-node1:9200
      - ELASTICSEARCH_HOSTS=http://es-node1:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - es-net

volumes:
  esdata:
    driver: local
networks:
  es-net:
    driver: bridge